# Generated by Django 5.1.6 on 2025-02-08 13:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a1e45797-611f-437e-ad2a-f4aa51de2eba'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
